on: ['push', 'pull_request']

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [ '10', '11', '12' ]
      name: Node ${{ matrix.node }}
      steps:
        - uses: actions/checkout@v2

        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}

        - name: Install dependencies
          run: npm ci
            
        - name: Execute tests
          run: npm build
            
        # - name: SonarCloud Scan
        #   uses: sonarsource/sonarcloud-github-action@master
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}